---
# tasks file for bigip-ui-banner
- name: Set the UI Login banner for the BIG-IP
  bigip_sys_global:
    security_banner: yes
    # banner_text: "{{ bigip_banner.text }}"
    banner_text: |
      ****************************************************** 
      **            "{{ inventory_hostname[0:11] }}"/"{{ inventory_hostname[0:11] }}"               **
      **             F5 vBIG-IP - 15.1.2.1                **
      **  Login Required. If you have not been provided   **
      **     with permission to access this device,       **  
      **            disconnect immediately!               **
      **       Unauthorized access is prohibited.         **
      **                                                  ** 
      ****************************************************** 
    provider: "{{ cli }}"
    state: "{{ bigip_banner.state }}"
  delegate_to: localhost
  tags: bigip-ui-banner