---
# tasks file for bigip-sshd-banner
- name: Set the sshd banner for the BIG-IP
  bigip_device_sshd:
    banner: "{{ bigip_banner.status }}"
    banner_text: |
      ****************************************************** 
      **            "{{ bigip_banner.bipip01_hostname }}"/"{{ bigip_banner.bipip02_hostname }}"               **
      **             F5 vBIG-IP - 15.1.2.1                **
      **  Login Required. If you have not been provided   **
      **     with permission to access this device,       **  
      **            disconnect immediately!               **
      **       Unauthorized access is prohibited.         **
      **                                                  ** 
      ****************************************************** 
    provider: "{{ cli }}"
  delegate_to: localhost
  tags: bigip-ssh-banner