- name: CREATE F5 BIGIP NODES
  hosts: eve_bigip
  gather_facts: false  
  connection: local
  collections: 
    - f5networks.f5_modules
    
  vars:
    cli:
      server: "{{ inventory_hostname }}"
      user: "{{ ansible_user }}"
      password: "{{ ansible_pass }}"
      server_port: "{{ port }}"
      validate_certs: no

  tasks:
    - name: CONFIGURE BIGIP NODES
      include_role: 
        name: bigip-vip-pool
        tasks_from: nodes.yml

    # - name: CONFIGURE BIGIP NODES
    #   include_role: 
    #     name: bigip-node
