- name: CREATE F5 BIGIP POOL
  hosts: eve_bigip
  gather_facts: false  
  connection: local
  collections: 
    - f5networks.f5_modules
    
  vars:
    cli:
      server: "{{ inventory_hostname }}"
      user: "{{ ansible_user }}"
      password: "{{ ansible_pass }}"
      server_port: "{{ port }}"
      validate_certs: no

  tasks:
    - name: CONFIGURE BIGIP POOL
      include_role: 
        name: bigip-vip-pool
        tasks_from: pools.yml

    - name: CONFIGURE BIGIP POOL MEMBERS      
      include_role:
        name: bigip-vip-pool
        tasks_from: pool_members.yml

    # - name: CONFIGURE BIGIP POOL
    #   include_role: 
    #     name: bigip-pool
