- name: SHOW VERSION FOR THE ASA FW
  hosts: asa-core-fw01.gcp01
  connection: network_cli
  gather_facts: no
  strategy: linear
  
  # ansible-playbook -i inventory.yml show_version_asa.yml -u admin -k
  
  tasks:
    - name: Get the version of the ASA FW 
      asa_command:
        commands:
          - show version | grep Ver
      register: output

    - name: Show the version of the ASA FW
      debug: 
        msg: "{{ output.stdout_lines }}"
