- name: F5 BIGIP IRULES Creation
  hosts: eve_bigip
  gather_facts: false  
  connection: local
  collections: 
    - f5networks.f5_modules
    
  vars:
    cli:
      server: "{{ inventory_hostname }}"
      user: "{{ ansible_user }}"
      password: "{{ ansible_pass }}"
      server_port: "{{ port }}"
      validate_certs: no

  tasks:
    # - name: Add the iRule contained in template irule.tcl to the LTM module
    #   bigip_irule:
    #     content: "{{ lookup('template', 'https_redirect_irule.tcl') }}"
    #     module: ltm
    #     name: sys_https_redirect
    #     partition: TENANT_1
    #     state: present
    #     provider: "{{ cli }}"
    #   delegate_to: localhost

    # - name: Add the iRule contained in static file irule.tcl to the LTM module
    #   bigip_irule:
    #     module: ltm
    #     name: sys_https_redirect
    #     src: https_redirect_irule.tcl
    #     state: present
    #     provider: "{{ cli }}"
    #   delegate_to: localhost