- name: F5 BIGIP PLAYBOOK TO RESTORE F5 BIGIP VIA UCS FILE 
  hosts: eve_bigip
  gather_facts: false  
  connection: local
  collections: 
    - f5networks.f5_modules
  
  vars:
    cli:
      server: "{{ inventory_hostname }}"
      user: "{{ ansible_user }}"
      password: "{{ ansible_pass }}"
      server_port: "{{ port }}"
      validate_certs: no

  tasks:
    - name: Upload UCS
      bigip_ucs:
        ucs: ~/f5-bigip-project/tmp/eveF5_backup_26-05-2021.ucs
        state: present
        provider: "{{ cli }}"
      delegate_to: localhost

    - name: Install (upload, install) UCS.
      bigip_ucs:
        ucs: ~/f5-bigip-project/tmp/eveF5_backup_26-05-2021.ucs
        state: installed
        provider: "{{ cli }}"
      delegate_to: localhost

    - name: Install (upload, install) UCS without installing the license portion
      bigip_ucs:
        ucs: ~/f5-bigip-project/tmp/eveF5_backup_26-05-2021.ucs
        state: installed
        no_license: yes
        provider: "{{ cli }}"
      delegate_to: localhost

    - name: Install (upload, install) UCS except the license, and bypassing the platform check
      bigip_ucs:
        ucs: ~/f5-bigip-project/tmp/eveF5_backup_26-05-2021.ucs
        state: installed
        no_license: yes
        no_platform_check: yes
        provider: "{{ cli }}"
      delegate_to: localhost

    - name: Install (upload, install) UCS using a passphrase necessary to load the UCS
      bigip_ucs:
        ucs: ~/f5-bigip-project/tmp/eveF5_backup_26-05-2021.ucs
        state: installed
        passphrase: MyPassphrase1234
        provider: "{{ cli }}"
      delegate_to: localhost

    - name: Remove uploaded UCS file
      bigip_ucs:
        ucs: ~/f5-bigip-project/tmp/eveF5_backup_26-05-2021.ucs
        state: absent
        provider: "{{ cli }}"
      delegate_to: localhost