---

- name: Retrieve interfaces
  hosts: cisco_sandbox
  gather_facts: no
  connection: network_cli
  vars: 
    nxos_provider:
      hostname: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      dev_os: "{{ ansible_network_os }}"
      optional_args:
        port: "{{ ansible_port }}"

  tasks:
    #- name: get facts from device
    #  napalm_get_facts:
    #    hostname: "{{ ansible_host }}"
    #    username: "{{ ansible_user }}"
    #    password: "{{ ansible_password }}"
    #    dev_os: "{{ ansible_network_os }}"
    #    filter: facts
    #    optional_args:
    #      port: "{{ ansible_port }}"
    #  register: result

    #- name: print data
    #  debug: var=result

    #- name: Napalm Getters 
    #  napalm_get_facts:
    #    provider: "{{ nxos_provider }}"
    #    filter: 
    #      #- "mac_address_table"
    #      #- "interfaces"
    #      #- "ntp_servers"
    #      - "config"
    #  register: naplam_getters

    #- name: Printing Napalm Getters
    #  debug:
    #    msg: "{{ naplam_getters.ansible_facts.napalm_config.running.split('\n') }}"

    - name: Configure NTP on NXOS
      napalm_install_config:
        provider: "{{ nxos_provider }}"
        config_file: "~/ansible-naplam/configs/{{ inventory_hostname }}.conf"
        commit_changes: True 
        replace_config: True
        #commit_changes: '{{ commit_changes }}'
        #replace_config: '{{ replace_config }}'
        get_diffs: False
        #diff_file: "~/ansible-naplam/diff_files/{{ inventory_hostname}}.diff"

