---

# Task to create a virtual server 
- name: Create a Virtual Server
  bigip_virtual_server:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    source: "{{ item.source }}"
    destination: "{{ item.destination }}"
    port: "{{ item.port }}"
    pool: "{{ item.pool }}"
    partition: "{{ item.partition | upper }}"
    snat: "{{ item.snat }}"
    state: "{{ item.state }}"
    # type: "{{ item.type }}"
    # port_translation: "{{ item.port_translation }}"
    # source_port: "{{ item.source_port }}"
    # all_profiles: "{{ item.all_profiles }}"
    provider: "{{ cli }}"
  delegate_to: localhost
  with_items: "{{ virtual_server }}"
  tags: virtual_server